### ISSUE TITLE
[tweak] Profile Page, Activity Log and Post Dialog

### ISSUE THREAD

**Issue by GuardianMajor** [dtinth/dark-facebook#25]
### For new problems, please [create a new issue](https://github.com/dtinth/dark-facebook/issues/new) instead of commenting on this one.

---

Hello my friend, great job on the second generation, for a WIP its excellent, good work. I gave a run as promised and I am sharing a few nice to have tweaks. I am going to open them separately to make it easier.

Profile Page - Recently Activity
![recent_activity](https://f.cloud.github.com/assets/5274181/2440187/308ec3a8-ae05-11e3-8d3e-378f884c2ae8.png)

Before the mouse-over it looks beautiful but after mouse-over you get that ugly gray and the scope menu is weird black and well it just looks bad. I think a tweak to make the colors more consistent would make it truly spectacular.

**Comment by GuardianMajor** [comment]
Then it brings to the profile page status box. I see that on the homepage the status box has a beautiful header and the color is consistent but on the profile page its grey and not consistent, can we get that to match as well.

![profile_status](https://f.cloud.github.com/assets/5274181/2440224/af71023a-ae05-11e3-9208-6ad78bb3b063.png)

**Comment by GuardianMajor** [comment]
When you scroll down a bit, you get to those stupid life event boxes and their color totally ruins the overall look. Also the black down arrow on the timeline actions blend to the black color and are not seen anymore. Also you get these grey washed out sections where you can barely see the text and the boxy grey just totally makes the page look ugly.

![timeline_elements](https://f.cloud.github.com/assets/5274181/2440280/3cbbdab6-ae06-11e3-8557-6388573fad37.png)

**Comment by GuardianMajor** [comment]
On the activity log page, you can see that the background of the main content is white and the text washes out and the menu actions are blacked out and look out of place. I have provided an example to show what I mean, but applies to all of them.

![activity_log](https://f.cloud.github.com/assets/5274181/2440313/9fc1bb1c-ae06-11e3-88fc-810f3f0fd3de.png)

**Comment by GuardianMajor** [comment]
When you try to post something, the interface is completely out of whack :) I grabbed a random example to show you what you I mean.

![facebook_dialog](https://f.cloud.github.com/assets/5274181/2440324/c4744420-ae06-11e3-81f5-3efa1ef8a4dc.png)

**Comment by GuardianMajor** [comment]
The very bottom of the profile page, where it tells you when you were born, like we need a reminder, you can see the text is completely blended out, you can select it (click and drag) and you will see it but otherwise, not visible, is that intentional or just forgot to define the color for the text?

![born_text](https://f.cloud.github.com/assets/5274181/2440541/b9119ec8-ae08-11e3-8057-7238989d5323.png)

**Comment by GuardianMajor** [comment]
I am across another breakage, god bless facebook, NOT. During the reporting mechanism, you can't see anything, see below:

![rep_1](https://f.cloud.github.com/assets/5274181/2443055/7b1111f6-ae2d-11e3-984d-05920680aae7.png)
![rep_2](https://f.cloud.github.com/assets/5274181/2443056/8074b0b2-ae2d-11e3-879b-89491916a8ca.png)
![rep_3](https://f.cloud.github.com/assets/5274181/2443057/854c3470-ae2d-11e3-89c2-3624164331b1.png)

**Comment by dtinth** [comment]
Thanks for your report! It's very useful to have screenshots. :+1:

When I have time I'll fix them.

If you encounter more problems with this style, please open a separate issue for each item, so that I can close each of them separately! Thanks again!

**Comment by GuardianMajor** [comment]
@dtinth 
You are always welcome my friend and thank you.

Accept my sincerest apologies, I originally thought about doing that and was going to then I hedged myself and decided to put them as separate posts here, I made the wrong call, I am sorry. In the future, separate they shall be.

Can I also ask you a favor that you modify the GM script to update to the latest build automatically instead of having to install it each time manually, that would be totally awesome if it was self updating.

**Comment by MALLER-LAGOON** [comment]
i'd have solved some of those problems. but i don't know where to let the code to apply it :/

**Comment by MALLER-LAGOON** [comment]
this is how it looks like the report and/or block window with my code fixed
![pantallazo](https://cloud.githubusercontent.com/assets/7074901/2531286/f0596ab8-b52f-11e3-96f4-64781c126bec.png)

**Comment by MALLER-LAGOON** [comment]
this is how it looks when i apply my fix to the birth date:

![pantallazo](https://cloud.githubusercontent.com/assets/7074901/2531551/7cf5c3f6-b533-11e3-9817-655b19425a15.png)

i know is not the best, but is something usefull.

**Comment by GuardianMajor** [comment]
@MALLER-LAGOON 
Good job, they look great. You have two choices, you can put the codes here and we can commit them, or you can commit them yourself and if accepted by @dtinth it will become part of the final code.

**Comment by MALLER-LAGOON** [comment]
i couldn't put the code on this textbox, so i uploaded to dropbox.

here u have the codes that i've got modified.by now:

https://www.dropbox.com/s/7r0t5ncnev5we6e/facebook_dark2.txt

i have a problem with the "a" definitions, so i will work on that later.

**Comment by dtinth** [comment]
@MALLER-LAGOON Hello! Thanks a lot for the fix. I'll review it.

For putting code, I recommend uploading it to http://gist.github.com/.

Please note that the code looks extremely chaotic because they are mostly generated, and I'm not good at writing documentation to describe how it works.

This user style is written in two languages, LESS and YAML, instead of CSS, so to apply your code, I would have to figure out what you have changed to the CSS file, and reverse-engineer it into LESS and YAML.

Fortunately, it's a very simple process, but unfortunately, for me it's hard to describe.

If you are interested in joining this project, please let me know, and then maybe we can arrange something like a TeamViewer session for pair programming.

---

To give you some insignt into how LESS and YAML plays in the development of dark-facebook, consider this LESS code:

``` less
:::popup-menu {
  background: @bg0;
  border: 1px solid @border1;
  &--item {
    &, &--text {
      .make-text-color;
    }
    border-color: @bg0;
    background-color: @bg0;
    &:hover, &--selected {
      border-color: @border3;
      background-color: @bg3;
    }
  }
  &--separator {
    border-color: @border1;
  }
  &--separator-bg {
    // like &--separator, but uses background color
    // instead of border color
    background: @border1;
  }
}
```

It looks like CSS, but notice the few differences here:
1. You see that I did not specify the color directly, but I used "variables." That made it easy when we want to change the colors in the future, or allowing multiple versions of the theme.
2. Rulesets are nested to make it easier to read.
3. The selector you see here is not Facebook's selector, but I made up a name for each of Facebook's component.

Since Facebook changes the selectors very frequently, breaking many Facebook themes, putting the selector directly in CSS/LESS files are not practical.

Instead, I use a separate file, a YAML file, to map these component name to Facebook selectors. They are grouped by where they are found, making it much easier to maintain than conventional styling process.

``` yaml
popup-menu(ui-menu):
  selector: ".uiMenu"
  info: "Commonly-used popup menus everywhere."
  found: |
    When clicking the edit button, next to the side-nav.
    The one that lets you add a navigation item to the favorites.
  children:
    item:
      selector: ".uiMenuItem a"
    separator:
      selector: ".uiMenuSeparator"

popup-menu(news-feed):
  selector: "._569t ._54ng"
  info: The popup menu found in news feeds.
  found: In the sort options in the news feed.
  children:
    item:
      selector: "._569t ._54nc"
    separator:
      selector: "._569t ._54ak"

popup-menu(mar2013):
  selector: "._54nf"
  children:
    item:
      selector: "._558b ._54nc"
      children:
        selected:
          selector: "._558b ._54ne ._54nc"
    separator:
      selector: "._558b ._54ak"
```

Facebook has so many versions of popup menus. [There are at least 6](https://github.com/dtinth/dark-facebook/blob/dfb2/src/components/popup-menu.yml).

With this approach, I can group each version separately, and yet refer to them at the same place.
